jobs:
  - name: Test sgh-eltern.de
    plan:
    - get: ci-tasks
      trigger: false
    - get: Every Monday and Thursday
      trigger: true
    - task: Execute Test on Ghost Inspector
      file: ci-tasks/ci/fetch-result/task.yml
      params:
        url: https://api.ghostinspector.com/v1/suites/5980dea61599c8322646cba8/execute/?apiKey=((ghost.api-key))
    - task: Evaluate Test Results
      file: ci-tasks/ci/evaluate-result/task.yml

  - name: Test wiki.eltern-sgh.de
    plan:
    - get: ci-tasks
      trigger: false
    - get: Every Tuesday and Friday
      trigger: true
    - task: Execute Test on Ghost Inspector
      file: ci-tasks/ci/fetch-result/task.yml
      params:
        url: https://api.ghostinspector.com/v1/suites/5980e429b1c3a81c61f4d35b/execute/?apiKey=((ghost.api-key))
    - task: Evaluate Test Results
      file: ci-tasks/ci/evaluate-result/task.yml

  - name: Test geb-herrenberg.de
    plan:
    - get: ci-tasks
      trigger: false
    - get: Every Wednesday and Saturday
      trigger: true
    - task: Execute Test on Ghost Inspector
      file: ci-tasks/ci/fetch-result/task.yml
      params:
        url: https://api.ghostinspector.com/v1/suites/5980f61fb1c3a81c61f4d6ac/execute/?apiKey=((ghost.api-key))
    - task: Evaluate Test Results
      file: ci-tasks/ci/evaluate-result/task.yml

  - name: Test freunde-sgh.de
    plan:
    - get: ci-tasks
    - get: Every Sunday
      trigger: false
      trigger: true
    - task: Execute Test on Ghost Inspector
      file: ci-tasks/ci/fetch-result/task.yml
      params:
        url: https://api.ghostinspector.com/v1/suites/5980f616b1c3a81c61f4d6ab/execute/?apiKey=((ghost.api-key))
    - task: Evaluate Test Results
      file: ci-tasks/ci/evaluate-result/task.yml

resources:
  - name: ci-tasks
    type: git
    source:
      uri: https://github.com/sgh-eltern/wiki.git
      paths: [ ci/* ]
      branch: master

  - name: Every Monday and Thursday
    type: time
    source:
      interval: 24h
      days: [Monday, Thursday]

  - name: Every Tuesday and Friday
    type: time
    source:
      interval: 24h
      days: [Tuesday, Friday]

  - name: Every Wednesday and Saturday
    type: time
    source:
      interval: 24h
      days: [Wednesday, Saturday]

  - name: Every Sunday
    type: time
    source:
      interval: 24h
      days: [Sunday]
